apiVersion: v1
kind: Secret
metadata:
  name: rabbitmq-secrets
  namespace: fase4
  labels:
    app.kubernetes.io/name: rabbitmq
    app.kubernetes.io/part-of: fase4-shared-messaging
type: Opaque
stringData:
  rabbitmq-user: "admin"
  rabbitmq-pass: "admin123"
  rabbitmq-vhost: "fiap"
