apiVersion: v1
kind: Secret
metadata:
  name: users-api-secrets
  namespace: users-api
type: Opaque
stringData:
  NOTIFICATION_QUEUE_URL: "https://sqs.us-east-1.amazonaws.com/ACCOUNT_ID/notification-queue"
  COGNITO_CLIENT_ID: "4pt4nk3r4ubhd8855b22ar2tse"
  COGNITO_USER_POOL_ID: "us-east-1_ZDPqjaUp4"