apiVersion: v1
kind: Secret
metadata:
  name: app-secrets
  namespace: fase4
type: Opaque
stringData:
  db-connection: "Host=postgres;Port=5432;Database=users_db;Username=postgres;Password=postgres123;"
  db-password: "postgres123"
  jwt-secret: "your-super-secret-key-at-least-32-characters-long!"
  jwt-issuer: "ms-users-api"
  jwt-audience: "ms-users-api-client"
  jwt-key-id: "ms-users-api-signing-key"
